feat: create user account
whizzes/nexus pull request #8
Opened 2022-03-31 22:58 UTC by Michael-Liendo

2022-03-31 23:12 UTC, EstebanBorai requested changes
Thanks so much! Here im suggesting some changes that could improve complexity and best practices. Let me know if you have an issue please.

2022-03-31 23:12 UTC, EstebanBorai commented on src/lib/components/Authenticate/Login.svelte
> +  <form on:submit={() => console.log('Submit')}>
This will be taken care of in a next PR using https://github.com/whizzbit/nexus-api/commit/372d062c78a889c9f2fb4b5a5dfdbc0fbc751f72

2022-03-31 23:12 UTC, EstebanBorai commented on src/lib/components/Authenticate/SignUp.svelte
> +  </div>
You can use [Event forwarding](https://svelte.dev/tutorial/event-forwarding) when you expect the parent component to handle this event.

```suggestion
  <div>
    <button on:click>Login?</button>
  </div>
```

2022-03-31 23:12 UTC, EstebanBorai commented on src/lib/components/Authenticate/SignUp.svelte
> +  </div>
The `on:click` event is generic, we can't tell if this event is meant to be for changing form.
I suggest dispatching another event, one that describes the use case:

```suggestion
  <div>
    <button on:click={() => dispatch('toggleForm')}>Login?</button>
  </div>
```

The `toggleForm` event could be used to toggle the form between Login/Signup.

2022-03-31 23:12 UTC, EstebanBorai commented on src/lib/components/Authenticate/index.svelte
> +  }
We only have 2 forms and 2 possible values. A boolean fits very well for this implementation. I suggest relying on a use case and discard the other for simplicity.

```suggestion
  let isLogin = true;

  function handleToggleForm() {
    isLogin = !isLogin;
  }
```

2022-03-31 23:12 UTC, EstebanBorai commented on src/lib/components/Authenticate/index.svelte
> +  {/if}
As we are using a boolean, there's only 2 possible values here. Theres no need for a second `if`.

```suggestion
  {#if isLogin}
    <Login on:toggleForm={handleToggleForm} />
  {:else}
    <SignUp on:toggleForm={handleToggleForm} />
  {/if}
```

2022-03-31 23:27 UTC, EstebanBorai approved these changes
LGTM!

2022-03-31 23:30 UTC, Michael-Liendo commented
> LGTM!

thanks!

2022-04-02 00:16 UTC, EstebanBorai commented
The CI workflow to build the project fails because the `lib/graphql/schema.ts` file is missing. This is actually expected becase we don't commit the schema file. This could be generated as part of the CI workflow at some point, so I will merge this anyways.

2022-04-02 00:17 UTC, merged